name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha de commits
        uses: Platane/snk@v2
        with:
          github_user_name: berTrapp
          outputs: dist/snake.svg

      - name: Adicionar a cobrinha ao repositório
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
